Return `loss` from validation_step return instead of `val_loss`.
Super weird that when I try tensorboarding image in training_step()
then process_outputs() returns an error
> RuntimeError: No `loss` value in the dictionary returned from
> `model.training_step()`.
But I just